{
 "title": "Mattermost Server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Duration in ms" }
   ],
   "targets": [
    {
     "expr": "rate(mattermost_http_request_duration_seconds_sum[5m])/rate(mattermost_http_request_duration_seconds_count[5m])*1000",
     "legendFormat": "Average request duration in ms"
    }
   ]
  },
  {
   "title": "Relative amount of HTTP errors",
   "type": "graph",
   "description": "Percentual amount of HTTP errors per HTTP requests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(rate(mattermost_http_errors_total[5m])/rate(mattermost_http_requests_total[5m]))  ",
     "legendFormat": "Percentage of errors per request"
    }
   ]
  },
  {
   "title": "Amount of websockets",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mattermost_http_websockets_total",
     "legendFormat": "Amount of websockets"
    }
   ]
  }
 ]
}